<a href="https://colab.research.google.com/github/Takagon/github_takagon_test/blob/master/NL2ML_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import math
import numpy as np
from sklearn.metrics import confusion_matrix

In [40]:
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
y = np.array([0,1,1,1,1,1,1,1])

In [45]:
def perceptron(w,x):
  xT = np.array(x, ndmin=2).T
  h = np.dot(w[:3], xT)+w[3]
  return 1*(h>0)

In [56]:
w = np.random.rand(4)
learning_rate = 0.01
epoch = 100
print(w)

[0.27176916 0.31619156 0.22000378 0.19310165]


In [48]:
y_pred = perceptron(w,X)
confusion_matrix(y, y_pred)

array([[0, 1],
       [0, 7]])

In [57]:
for i in range(epoch):
    for j in range(len(y)):
        error = y[j] - perceptron(w, X[j])
        for k in range(len(w)):
            if k==3:
                w[k] += error*learning_rate*1
            else:
                w[k] += error*learning_rate*X[j,k]
print(w)

[ 0.27176916  0.31619156  0.22000378 -0.00689835]


In [64]:
y_pred = perceptron(w,X)
confusion_matrix(y, y_pred)

array([[1, 0],
       [0, 7]])

In [65]:
def sigmoid(h):
  return 1 / (1 + math.e**-h)

In [74]:
def tor_func(x):
  h = 0
  for i in range(3):
    h = h + w[i] * x[i]
  h += w[3]
  return sigmoid(h)

In [75]:
print(tor_func(np.array([0,0,0])))
print(tor_func(np.array([0,0,1])))
print(tor_func(np.array([0,1,0])))
print(tor_func(np.array([0,1,1])))
print(tor_func(np.array([1,0,0])))
print(tor_func(np.array([1,0,1])))
print(tor_func(np.array([1,1,0])))
print(tor_func(np.array([1,1,1])))

0.4982754198619688
0.5530756455109733
0.5767127327668243
0.6293191315955057
0.5658332653246033
0.618898275459054
0.6413118206878387
0.6902024945098549
